<table width="90%" border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#006699">
	<tr><td class="header" valign="bottom" align="center" rowspan="2"width="120">
	<img src="../images/swpppweb2.jpg" height="101" border="0" vspace="0" hspace="0" 
		alt="SWPPP Inspections"></td>
	<td nowrap valign="bottom" bgcolor="#006699"><br><br><br><br></td>
	</tr><tr bgcolor="#999999">
	<td><div class="white"><a href="../default.asp" class="head">Home</a> &nbsp; | &nbsp; 
	<a href="../static/about.asp" class="head">About Us</a> &nbsp; | &nbsp; 
	<a href="../static/contact.asp" class="head">Contact Us</a> &nbsp; | &nbsp; 
	<a href="../views/projects.asp" class="head">Inspections</a> &nbsp; | &nbsp; 
	<a href="../admin/default.asp" class="head">Admin</a></div></td></tr></TABLE>
<TABLE width="80%" align="center" border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#FFFFF">
	<tr bgcolor="white" style="margin-left:10%;"><td><br>