<div class="header-top">
<div class="fl">
	<a href="../default.asp"><img src="../images/swpppweb2.jpg" height="100" border="0" vspace="0" hspace="0" alt="SWPPP Inspections"></a>
</div>
<h2>SWPPP Inspections</h2>
</div>
<div class="cleaner"></div>
<div class="header-nav-bar">
  <div class="header-nav three columns alpha"><a href="../about.asp">About Us</a></div>
  <div class="header-nav three columns"><a href="../contact.asp">Contact Us</a></div>
  <div class="header-nav three columns"><a href="../views/projects.asp">Inspections</a></div>
  <div class="header-nav three columns omega"><a href="../admin/default.asp">Admin</a></div>
</div>
<div class="cleaner"></div>