<table width="90%" border="0" cellpadding="0" cellspacing="0" align="center">
	<tr align=center> 
	<td class="header" align="center" width=570 colspan=2>
		<a href="default.asp"><img align="center" src="images/swpppweb2.jpg" width="600" 
			border="0" vspace="4" hspace="0" alt="SWPPP Inspections"></a></td>
	</tr><tr style="height:40;" bgcolor="#999999"><td colspan=2><div class="white">
	<TABLE width=100%>
		<TR>
			<TD>&nbsp;</TD>
			<TD><a href="static/about.asp" class="head">about us</a></TD>
			<TD>&nbsp; | &nbsp;</TD>
			<TD><a href="static/contact.asp" class="head">contact us</a></TD>
			<TD>&nbsp; | &nbsp;</TD>
			<TD><a href="views/projects.asp" class="head">log in</a></TD>
			<TD>&nbsp; | &nbsp;</TD>
			<TD><a href="admin/default.asp" class="head">admin</a></TD>
			<TD>&nbsp;</TD>
		</TR>
	</TABLE>
		</div></td></tr>