<table width="90%" border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#FFFFFF>
	<tr><td class="header" valign="bottom" align="center" rowspan="2"width="120">
	<img src="images/swpppweb2.jpg" height="101" border="0" vspace="0" hspace="0" 
		alt="SWPPP Inspections"></td>
	<td nowrap valign="bottom" bgcolor="#006699"><br><br><br><br></td>
	</tr><tr bgcolor="#999999">
	<td><div class="white"><a href="default.asp" class="head">home</a> &nbsp; | &nbsp; 
	<a href="static/about.asp" class="head">about us</a> &nbsp; | &nbsp; 
	<a href="static/contact.asp" class="head">contact us</a> &nbsp; | &nbsp; 
	<a href="views/projects.asp" class="head">log in</a> &nbsp; | &nbsp; 
	<a href="admin/default.asp" class="head">admin</a></div></td></tr></TABLE>
<table width="90%" border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#FFFFFF>
	<tr><td style="margin-left:10%;" colspan=2>